name = "TFC-Upgrade"
author = "isbest"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "638c21f5d101976feb3d82b170accb291bc45414397cad407fae81b3af58e342"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
