name = "TFC-Upgrade"
author = "isbest"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1b0c548e276cd6592154ceceb9f82069340974a7e395f371924d2c8edf91754"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
